<a href="https://colab.research.google.com/github/MrsHorrid/Birthday-site/blob/main/MOVIE%20RECOMMENDER%20CORRELATION%20MATRIX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas

ratings_features = ["user_id", "movieId", "rating", "timestamp"]

ratings_dataframe = pandas.read_csv("ratings.csv",
                                    names = ratings_features)

ratings_dataframe

       user_id  movieId  rating   timestamp
0       userId  movieId  rating   timestamp
1            1        1     4.0   964982703
2            1        3     4.0   964981247
3            1        6     4.0   964982224
4            1       47     5.0   964983815
...        ...      ...     ...         ...
100832     610   166534     4.0  1493848402
100833     610   168248     5.0  1493850091
100834     610   168250     5.0  1494273047
100835     610   168252     5.0  1493846352
100836     610   170875     3.0  1493846415

[100837 rows x 4 columns]

In [8]:
ratings_dataframe = ratings_dataframe.drop(ratings_dataframe.index[0])

ratings_dataframe

       user_id movieId rating   timestamp
1            1       1    4.0   964982703
2            1       3    4.0   964981247
3            1       6    4.0   964982224
4            1      47    5.0   964983815
5            1      50    5.0   964982931
...        ...     ...    ...         ...
100832     610  166534    4.0  1493848402
100833     610  168248    5.0  1493850091
100834     610  168250    5.0  1494273047
100835     610  168252    5.0  1493846352
100836     610  170875    3.0  1493846415

[100836 rows x 4 columns]

In [9]:
ratings_dataframe = ratings_dataframe.astype("float")

ratings_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 1 to 100836
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user_id    100836 non-null  float64
 1   movieId    100836 non-null  float64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  float64
dtypes: float64(4)
memory usage: 3.1 MB

In [10]:
movies_dataframe = pandas.read_csv("movies.csv")

movies_dataframe

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [11]:
movie_titles_dataframe = movies_dataframe[["movieId", "title"]]

movie_titles_dataframe

      movieId                                      title
0           1                           Toy Story (1995)
1           2                             Jumanji (1995)
2           3                    Grumpier Old Men (1995)
3           4                   Waiting to Exhale (1995)
4           5         Father of the Bride Part II (1995)
...       ...                                        ...
9737   193581  Black Butler: Book of the Atlantic (2017)
9738   193583               No Game No Life: Zero (2017)
9739   193585                               Flint (2017)
9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741   193609        Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 2 columns]

In [12]:
movie_titles_dataframe["movieId"] = movie_titles_dataframe["movieId"].astype(str).astype(float)

movie_titles_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   float64
 1   title    9742 non-null   object
dtypes: float64(1), object(1)
memory usage: 152.3+ KB

<ipython-input-12-e6ddfe3b91fe>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_titles_dataframe["movieId"] = movie_titles_dataframe["movieId"].astype(str).astype(float)

In [13]:
merged_dataframe = pandas.merge(ratings_dataframe , movie_titles_dataframe, on = "movieId")

merged_dataframe

,user_id,movieId,rating,timestamp,title
0,1.0,1.0,4.0,9.649827e+08,Toy Story (1995)
1,5.0,1.0,4.0,8.474350e+08,Toy Story (1995)
2,7.0,1.0,4.5,1.106636e+09,Toy Story (1995)
3,15.0,1.0,2.5,1.510578e+09,Toy Story (1995)
4,17.0,1.0,4.5,1.305696e+09,Toy Story (1995)
...,...,...,...,...,...
100831,610.0,160341.0,2.5,1.479546e+09,Bloodmoon (1997)
100832,610.0,160527.0,4.5,1.479545e+09,Sympathy for the Underdog (1971)
100833,610.0,160836.0,3.0,1.493845e+09,Hazard (2005)
100834,610.0,163937.0,3.5,1.493849e+09,Blair Witch (2016)
100835,610.0,163981.0,3.5,1.493850e+09,31 (2016)

In [14]:
merged_dataframe.groupby("movieId")["rating"].count().sort_values(ascending= False)

movieId
356.0       329
318.0       317
296.0       307
593.0       279
2571.0      278
           ...
4093.0        1
4089.0        1
58351.0       1
4083.0        1
193609.0      1
Name: rating, Length: 9724, dtype: int64

In [15]:
crosstab = merged_dataframe.pivot_table(values = "rating",
                             index = "user_id",
                             columns = "title",
                             fill_value = 0)

crosstab

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]Â² (2009),[REC]Â³ 3 GÃ©nesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),Â¡Three Amigos! (1986),Ã€ nous la libertÃ© (Freedom for Us) (1931)
user_id,,,,,,,,,,,,,,,,,,,,,
1.0,0,0,0.0,0,0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,4.0,0
2.0,0,0,0.0,0,0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0
3.0,0,0,0.0,0,0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0
4.0,0,0,0.0,0,0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0
5.0,0,0,0.0,0,0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606.0,0,0,0.0,0,0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0
607.0,0,0,0.0,0,0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0
608.0,0,0,0.0,0,0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,4.5,3.5,0.0,0.0,0
609.0,0,0,0.0,0,0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0
610.0,4,0,0.0,0,0,0.0,0.0,0,3.5,0.0,...,0.0,4.0,3.5,3,0,0.0,2.0,1.5,0.0,0

In [17]:
x = crosstab.T
x

user_id,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,...,601.0,602.0,603.0,604.0,605.0,606.0,607.0,608.0,609.0,610.0
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Salem's Lot (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Til There Was You (1997),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,0.0,0.0,0.0,4.5,0.0,0.0
xXx (2002),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,2.0
xXx: State of the Union (2005),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5
Â¡Three Amigos! (1986),4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ã€ nous la libertÃ© (Freedom for Us) (1931),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
from sklearn.decomposition import TruncatedSVD

NUMBER_OF_COMPONENTS = 12

singular_value_decomposition = TruncatedSVD(n_components= NUMBER_OF_COMPONENTS,
             random_state = 1)

matrix = singular_value_decomposition.fit_transform(x)

matrix

array([[ 5.55459718e-01,  8.08733634e-01, -3.70669991e-01, ...,
         3.19937608e-01, -3.90969969e-01,  5.73960805e-01],
       [ 2.34857543e-01,  4.86997987e-02,  2.82644178e-02, ...,
        -2.99135079e-02,  6.25107705e-02,  1.71349143e-02],
       [ 2.51207088e-01, -4.86045181e-03, -1.37795758e-02, ...,
         1.05460242e-02,  9.33327746e-02, -2.20099534e-03],
       ...,
       [ 9.35396233e-01,  9.31467402e-01, -1.29725391e-02, ...,
         5.67912123e-01, -6.36544601e-01,  1.26634956e+00],
       [ 6.50333276e+00, -2.71457844e+00, -2.10303281e+00, ...,
         2.33172763e+00,  1.00801451e+00, -4.03452518e+00],
       [ 3.13533586e-02, -4.36066605e-02,  3.28701125e-03, ...,
         2.01571142e-02,  4.63352403e-02,  1.91669167e-02]])

In [21]:
import numpy

correlation_matrix = numpy.corrcoef(matrix)

correlation_matrix

array([[ 1.        ,  0.22587598,  0.32009292, ...,  0.77096864,
        -0.09526227, -0.13554033],
       [ 0.22587598,  1.        ,  0.93576858, ...,  0.09653785,
         0.02366272, -0.24070855],
       [ 0.32009292,  0.93576858,  1.        , ...,  0.09387149,
         0.18904241,  0.01821163],
       ...,
       [ 0.77096864,  0.09653785,  0.09387149, ...,  1.        ,
        -0.10391862, -0.15732556],
       [-0.09526227,  0.02366272,  0.18904241, ..., -0.10391862,
         1.        ,  0.35063198],
       [-0.13554033, -0.24070855,  0.01821163, ..., -0.15732556,
         0.35063198,  1.        ]])

In [22]:
movies_titles = crosstab.columns

movies_titles

Index([''71 (2014)', ''Hellboy': The Seeds of Creation (2004)',
       ''Round Midnight (1986)', ''Salem's Lot (2004)',
       ''Til There Was You (1997)', ''Tis the Season for Love (2015)',
       ''burbs, The (1989)', ''night Mother (1986)',
       '(500) Days of Summer (2009)', '*batteries not included (1987)',
       ...
       'Zulu (2013)', '[REC] (2007)', '[REC]Â² (2009)',
       '[REC]Â³ 3 GÃ©nesis (2012)',
       'anohana: The Flower We Saw That Day - The Movie (2013)',
       'eXistenZ (1999)', 'xXx (2002)', 'xXx: State of the Union (2005)',
       'Â¡Three Amigos! (1986)', 'Ã€ nous la libertÃ© (Freedom for Us) (1931)'],
      dtype='object', name='title', length=9719)

In [24]:
movies_list = list(movies_titles)

movies_list

["'71 (2014)",
 "'Hellboy': The Seeds of Creation (2004)",
 "'Round Midnight (1986)",
 "'Salem's Lot (2004)",
 "'Til There Was You (1997)",
 "'Tis the Season for Love (2015)",
 "'burbs, The (1989)",
 "'night Mother (1986)",
 '(500) Days of Summer (2009)',
 '*batteries not included (1987)',
 '...All the Marbles (1981)',
 '...And Justice for All (1979)',
 '00 Schneider - Jagd auf Nihil Baxter (1994)',
 '1-900 (06) (1994)',
 '10 (1979)',
 '10 Cent Pistol (2015)',
 '10 Cloverfield Lane (2016)',
 '10 Items or Less (2006)',
 '10 Things I Hate About You (1999)',
 '10 Years (2011)',
 '10,000 BC (2008)',
 '100 Girls (2000)',
 '100 Streets (2016)',
 '101 Dalmatians (1996)',
 '101 Dalmatians (One Hundred and One Dalmatians) (1961)',
 "101 Dalmatians II: Patch's London Adventure (2003)",
 '101 Reykjavik (101 ReykjavÃ­k) (2000)',
 '102 Dalmatians (2000)',
 '10th & Wolf (2006)',
 '10th Kingdom, The (2000)',
 '10th Victim, The (La decima vittima) (1965)',
 '11\'09"01 - September 11 (2002)',
 '11:14 (2003)',
 '11th Hour, The (2007)',
 '12 Angry Men (1957)',
 '12 Angry Men (1997)',
 '12 Chairs (1971)',
 '12 Chairs (1976)',
 '12 Rounds (2009)',
 '12 Years a Slave (2013)',
 '127 Hours (2010)',
 '13 Assassins (JÃ»san-nin no shikaku) (2010)',
 '13 Ghosts (1960)',
 '13 Going on 30 (2004)',
 '13 Hours (2016)',
 '13 Sins (2014)',
 '13 Tzameti (2005)',
 '13th (2016)',
 '13th Warrior, The (1999)',
 '1408 (2007)',
 '1492: Conquest of Paradise (1992)',
 '15 Minutes (2001)',
 '16 Blocks (2006)',
 '17 Again (2009)',
 '1776 (1972)',
 '18 Again! (1988)',
 '187 (One Eight Seven) (1997)',
 '1900 (Novecento) (1976)',
 '1941 (1979)',
 '1969 (1988)',
 '1984 (Nineteen Eighty-Four) (1984)',
 '2 Days in New York (2012)',
 '2 Days in Paris (2007)',
 '2 Days in the Valley (1996)',
 '2 Fast 2 Furious (Fast and the Furious 2, The) (2003)',
 '2 Guns (2013)',
 '20 Dates (1998)',
 '20 Feet from Stardom (Twenty Feet from Stardom) (2013)',
 '20 Million Miles to Earth (1957)',
 '20,000 Days on Earth (2014)',
 '20,000 Leagues Under the Sea (1916)',
 '20,000 Leagues Under the Sea (1954)',
 '200 Cigarettes (1999)',
 '2001 Maniacs (2005)',
 '2001: A Space Odyssey (1968)',
 '2010: The Year We Make Contact (1984)',
 '2012 (2009)',
 '2046 (2004)',
 '2048: Nowhere to Run (2017)',
 '21 (2008)',
 '21 Grams (2003)',
 '21 Jump Street (2012)',
 '21 Up (1977)',
 '21 and Over (2013)',
 '22 Jump Street (2014)',
 '24 Hour Party People (2002)',
 '25th Hour (2002)',
 '27 Dresses (2008)',
 '28 Days (2000)',
 '28 Days Later (2002)',
 '28 Up (1985)',
 '28 Weeks Later (2007)',
 '3 Days to Kill (2014)',
 '3 Extremes (Three... Extremes) (Saam gaang yi) (2004)',
 '3 Idiots (2009)',
 '3 Ninjas (1992)',
 '3 Ninjas Kick Back (1994)',
 '3 Ninjas Knuckle Up (1995)',
 '3 Ninjas: High Noon On Mega Mountain (1998)',
 '3 Women (Three Women) (1977)',
 '3 dev adam (Three Giant Men) (1973) ',
 '3-Iron (Bin-jip) (2004)',
 '30 Days of Night (2007)',
 '30 Minutes or Less (2011)',
 '300 (2007)',
 '3000 Miles to Graceland (2001)',
 '300: Rise of an Empire (2014)',
 '31 (2016)',
 '35 Up (1991)',
 '39 Steps, The (1935)',
 '3:10 to Yuma (1957)',
 '3:10 to Yuma (2007)',
 '4 Little Girls (1997)',
 '4 Months, 3 Weeks and 2 Days (4 luni, 3 saptamÃ¢ni si 2 zile) (2007)',
 '40 Days and 40 Nights (2002)',
 '40-Year-Old Virgin, The (2005)',
 '400 Blows, The (Les quatre cents coups) (1959)',
 '42 (2013)',
 '42 Up (1998)',
 '42nd Street (1933)',
 '47 Ronin (2013)',
 '48 Hrs. (1982)',
 '49 Up (2005)',
 '5 Centimeters per Second (ByÃ´soku 5 senchimÃªtoru) (2007)',
 '5 to 7 (2014)',
 '5,000 Fingers of Dr. T, The (1953)',
 '50 First Dates (2004)',
 '50/50 (2011)',
 '52 Pick-Up (1986)',
 '54 (1998)',
 '6 Days to Air: The Making of South Park (2011)',
 '61* (2001)',
 '6th Day, The (2000)',
 '6th Man, The (Sixth Man, The) (1997)',
 '7 Days in Hell (2015)',
 '7 Faces of Dr. Lao (1964)',
 '7th Voyage of Sinbad, The (1958)',
 '8 1/2 (8Â½) (1963)',
 '8 Heads in a Duffel Bag (1997)',
 '8 Mile (2002)',
 '8 Seconds (1994)',
 '8 Women (2002)',
 '8 Â½ Women (a.k.a. 8 1/2 Women) (a.k.a. Eight and a Half Women) (1999)',
 '800 Bullets (800 Balas) (2002)',
 '84 Charing Cross Road (1987)',
 '8MM (1999)',
 '9 (2009)',
 '9 1/2 Weeks (Nine 1/2 Weeks) (1986)',
 '9/11 (2002)',
 '96 Minutes (2011) ',
 '964 Pinocchio (1991)',
 '99 francs (2007)',
 '9to5: Days in Porn (a.k.a. 9 to 5: Days in Porn) (2008)',
 'A Bad Moms Christmas (2017)',
 'A Christmas Story Live! (2017)',
 'A Cosmic Christmas (1977)',
 'A Detective Story (2003)',
 "A Dog's Purpose (2017)",
 'A Flintstones Christmas Carol (1994)',
 'A German Life (2016)',
 'A Home at the End of the World (2004)',
 'A Man Called Blade (1977)',
 'A Man from Boulevard des Capucines (1987)',
 "A Merry Friggin' Christmas (2014)",
 "A Midsummer Night's Dream (2016)",
 'A Million Ways to Die in the West (2014)',
 'A Most Wanted Man (2014)',
 'A Perfect Day (2015)',
 'A Pigeon Sat on a Branch Reflecting on Existence (2014)',
 'A Plasticine Crow (1981)',
 'A Quiet Place (2018)',
 'A Silent Voice (2016)',
 'A Story of Children and Film (2013)',
 'A Street Cat Named Bob (2016)',
 'A Very Murray Christmas (2015)',
 'A Walk in the Woods (2015)',
 'A Wrinkle in Time (2018)',
 'A-Team, The (2010)',
 'A.I. Artificial Intelligence (2001)',
 'ABCs of Death, The (2012)',
 'ARQ (2016)',
 'AVP: Alien vs. Predator (2004)',
 'AVPR: Aliens vs. Predator - Requiem (2007)',
 'Abandoned, The (2006)',
 'Abbott and Costello Meet Frankenstein (1948)',
 'Abduction (2011)',
 'Abominable Dr. Phibes, The (1971)',
 'Abominable Snowman, The (Abominable Snowman of the Himalayas, The) (1957)',
 'About Adam (2000)',
 'About Last Night (2014)',
 'About Last Night... (1986)',
 'About Schmidt (2002)',
 'About Time (2013)',
 'About a Boy (2002)',
 'Above the Law (1988)',
 'Above the Rim (1994)',
 'Abraham Lincoln: Vampire Hunter (2012)',
 'Absence of Malice (1981)',
 'Absent-Minded Professor, The (1961)',
 'Absentia (2011)',
 'Absolute Power (1997)',
 'Absolutely Anything (2015)',
 'Abyss, The (1989)',
 'Accepted (2006)',
 'Accidental Spy, The (Dak miu mai shing) (2001)',
 'Accidental Tourist, The (1988)',
 'Accused, The (1988)',
 'Ace Ventura: Pet Detective (1994)',
 'Ace Ventura: When Nature Calls (1995)',
 'Ace in the Hole (Big Carnival, The) (1951)',
 'Aces: Iron Eagle III (1992)',
 'Acid House, The (1998)',
 'Across the Hall (2009)',
 'Across the Universe (2007)',
 'Act of Killing, The (2012)',
 'Act of Valor (2012)',
 'Action Jackson (1988)',
 "Adam and Eve (National Lampoon's Adam & Eve) (2005)",
 "Adam's Apples (Adams Ã¦bler) (2005)",
 "Adam's Rib (1949)",
 'Adanggaman (2000)',
 'Adaptation (2002)',
 'Addams Family Reunion (1998)',
 'Addams Family Values (1993)',
 'Addams Family, The (1991)',
 'Addicted to Love (1997)',
 'Addiction, The (1995)',
 'Adjustment Bureau, The (2011)',
 'Admission (2013)',
 'Adventureland (2009)',
 'Adventures Of Sherlock Holmes And Dr. Watson: The Twentieth Century Approaches (1986)',
 'Adventures in Babysitting (1987)',
 'Adventures in Plymptoons! (2011)',
 'Adventures of Baron Munchausen, The (1988)',
 'Adventures of Buckaroo Banzai Across the 8th Dimension, The (1984)',
 'Adventures of Elmo in Grouchland, The (1999)',
 'Adventures of Ford Fairlane, The (1990)',
 'Adventures of Huck Finn, The (1993)',
 'Adventures of Ichabod and Mr. Toad, The (1949)',
 'Adventures of Mary-Kate and Ashley, The: The Case of the Christmas Caper (1995)',
 'Adventures of Milo and Otis, The (Koneko monogatari) (1986)',
 'Adventures of Mowgli: The Kidnapping (1968)',
 'Adventures of Pinocchio, The (1996)',
 'Adventures of Pluto Nash, The (2002)',
 'Adventures of Priscilla, Queen of the Desert, The (1994)',
 'Adventures of Robin Hood, The (1938)',
 'Adventures of Rocky and Bullwinkle, The (2000)',
 'Adventures of Sebastian Cole, The (1998)',
 'Adventures of Sharkboy and Lavagirl 3-D, The (2005)',
 'Adventures of Tintin, The (2011)',
 'Advise and Consent (1962)',
 'Aelita: The Queen of Mars (Aelita) (1924)',
 'Aeon Flux (2005)',
 'Affair of Love, An (Liaison pornographique, Une) (1999)',
 'Affair of the Necklace, The (2001)',
 'Affair to Remember, An (1957)',
 'Afflicted (2013)',
 'Affliction (1997)',
 'Afonya (1975)',
 'Africa: The Serengeti (1994)',
 'African Cats (2011)',
 'African Queen, The (1951)',
 'Afro Samurai (2007)',
 'Afro Samurai: Resurrection (2009)',
 'After Earth (2013)',
 'After Hours (1985)',
 'After Life (Wandafuru raifu) (1998)',
 'After the Fox (Caccia alla volpe) (1966)',
 'After the Sunset (2004)',
 'After the Thin Man (1936)',
 'After the Wedding (Efter brylluppet) (2006)',
 'Afterglow (1997)',
 'Against All Odds (1984)',
 'Against the Ropes (2004)',
 'Age of Innocence, The (1993)',
 'Agent Cody Banks (2003)',
 'Agent Cody Banks 2: Destination London (2004)',
 'Agnes of God (1985)',
 'Agony and the Ecstasy, The (1965)',
 'Agora (2009)',
 'Aguirre: The Wrath of God (Aguirre, der Zorn Gottes) (1972)',
 'Aileen: Life and Death of a Serial Killer (2003)',
 'Air America (1990)',
 'Air Bud (1997)',
 'Air Bud: Golden Receiver (1998)',
 'Air Force One (1997)',
 'Air I Breathe, The (2007)',
 'Air Up There, The (1994)',
 'Airborne (1993)',
 'Airheads (1994)',
 'Airplane II: The Sequel (1982)',
 'Airplane! (1980)',
 "Airport '77 (1977)",
 'Airport (1970)',
 'Airport 1975 (1974)',
 'Akeelah and the Bee (2006)',
 'Akira (1988)',
 "Akira Kurosawa's Dreams (Dreams) (1990)",
 'Aladdin (1992)',
 'Aladdin and the King of Thieves (1996)',
 'Alamo, The (1960)',
 'Alan Partridge: Alpha Papa (2013)',
 'Alaska (1996)',
 'Alaska: Spirit of the Wild (1997)',
 'Albatross (2011)',
 'Albino Alligator (1996)',
 'Alesha Popovich and Tugarin the Dragon (2004)',
 'Alex Cross (2012)',
 'Alex and Emma (2003)',
 'Alexander (2004)',
 'Alexander Nevsky (Aleksandr Nevskiy) (1938)',
 'Alfie (1966)',
 'Alfie (2004)',
 'Ali (2001)',
 'Ali G Indahouse (2002)',
 'Ali Wong: Baby Cobra (2016)',
 'Ali: Fear Eats the Soul (Angst essen Seele auf) (1974)',
 'Alias Betty (Betty Fisher et autres histoires) (2001)',
 'Alice (1990)',
 'Alice (2009)',
 'Alice (Neco z Alenky) (1988)',
 'Alice Adams (1935)',
 "Alice Doesn't Live Here Anymore (1974)",
 'Alice Through the Looking Glass (2016)',
 'Alice in Wonderland (1933)',
 'Alice in Wonderland (1951)',
 'Alice in Wonderland (2010)',
 'Alien (1979)',
 'Alien Contamination (1980)',
 'Alien Nation (1988)',
 'Alien from L.A. (1988)',
 'Alien: Covenant (2017)',
 'Alien: Resurrection (1997)',
 'Aliens (1986)',
 'AlienÂ³ (a.k.a. Alien 3) (1992)',
 'Alive (1993)',
 'All About Eve (1950)',
 'All About Lily Chou-Chou (Riri Shushu no subete) (2001)',
 'All About My Mother (Todo sobre mi madre) (1999)',
 'All About the Benjamins (2002)',
 'All Dogs Christmas Carol, An (1998)',
 'All Dogs Go to Heaven (1989)',
 'All Dogs Go to Heaven 2 (1996)',
 'All Good Things (2010)',
 'All Is Lost (2013)',
 'All Over the Guy (2001)',
 'All Quiet on the Western Front (1930)',
 'All Roads Lead to Rome (2016)',
 'All That Heaven Allows (1955)',
 'All That Jazz (1979)',
 'All This, and Heaven Too (1940)',
 'All Watched Over by Machines of Loving Grace (2011)',
 'All Yours (2016)',
 'All is Bright (2013)',
 'All of Me (1984)',
 'All or Nothing (2002)',
 'All the Boys Love Mandy Lane (2006)',
 "All the King's Men (1949)",
 "All the King's Men (2006)",
 "All the President's Men (1976)",
 'All the Pretty Horses (2000)',
 'All the Real Girls (2003)',
 'All the Right Moves (1983)',
 'All the Vermeers in New York (1990)',
 'All-Star Superman (2011)',
 'Allan Quatermain and the Lost City of Gold (1987)',
 'Allegro non troppo (1977)',
 'Alles Inklusive (2014)',
 'Alligator (1980)',
 'Allnighter, The (1987)',
 'Almost Famous (2000)',
 'Almost Heroes (1998)',
 'Almost an Angel (1990)',
 'Aloha (2015)',
 'Alone in the Dark (2005)',
 'Alone in the Dark II (2008)',
 'Along Came Polly (2004)',
 'Along Came a Spider (2001)',
 'Alpha (2018)',
 'Alpha Dog (2007)',
 'Alpha and Omega 3: The Great Wolf Games (2014)',
 'Alphaville (Alphaville, une Ã©trange aventure de Lemmy Caution) (1965)',
 'Altered (2006)',
 'Altered States (1980)',
 'Alvarez Kelly (1966)',
 'Alvin and the Chipmunks (2007)',
 'Alvin and the Chipmunks: Chipwrecked (2011)',
 'Alvin and the Chipmunks: The Squeakquel (2009)',
 'Always (1989)',
 'Always Watching: A Marble Hornets Story (2015)',
 'Amadeus (1984)',
 'Amanda Knox (2016)',
 'Amarcord (1973)',
 'Amateur (1994)',
 'Amazing Grace (2006)',
 'Amazing Grace and Chuck (1987)',
 'Amazing Panda Adventure, The (1995)',
 'Amazing Spider-Man, The (2012)',
 'Amazing Transparent Man, The (1960)',
 'Amazon Women on the Moon (1987)',
 "Amelie (Fabuleux destin d'AmÃ©lie Poulain, Le) (2001)",
 'Amen. (2002)',
 'Amer (2009)',
 "America's Sweethearts (2001)",
 'American Astronaut, The (2001)',
 'American Beauty (1999)',
 'American Buffalo (1996)',
 'American Carol, An (2008)',
 'American Dreamz (2006)',
 'American Drug War: The Last White Hope (2007)',
 'American Fable (2017)',
 'American Flyers (1985)',
 'American Friend, The (Amerikanische Freund, Der) (1977)',
 'American Gangster (2007)',
 'American Gigolo (1980)',
 'American Graffiti (1973)',
 'American Grindhouse (2010)',
 'American Hardcore (2006)',
 'American Haunting, An (2005)',
 'American Heist (2015)',
 'American History X (1998)',
 'American Hustle (2013)',
 'American Made (2017)',
 'American Me (1992)',
 'American Movie (1999)',
 'American Ninja (1985)',
 'American Outlaws (2001)',
 'American Pie (1999)',
 'American Pie 2 (2001)',
 'American Pie Presents Beta House (American Pie 6: Beta House) (2007)',
 'American Pie Presents The Naked Mile (American Pie 5: The Naked Mile) (2006)',
 'American Pie Presents: Band Camp (American Pie 4: Band Camp) (2005)',
 'American Pie Presents: The Book of Love (American Pie 7: The Book of Love) (2009)',
 'American Pop (1981)',
 'American President, The (1995)',
 'American Psycho (2000)',
 'American Psycho II: All American Girl (2002)',
 'American Reunion (American Pie 4) (2012)',
 'American Sniper (2014)',
 'American Splendor (2003)',
 'American Tail, An (1986)',
 'American Tail: Fievel Goes West, An (1991)',
 'American Ultra (2015)',
 'American Wedding (American Pie 3) (2003)',
 'American Werewolf in London, An (1981)',
 'American Werewolf in Paris, An (1997)',
 'American in Paris, An (1951)',
 'American, The (2010)',
 'American: The Bill Hicks Story (2009)',
 'Americanization of Emily, The (1964)',
 'Americathon (1979)',
 'Amistad (1997)',
 "Amityville 1992: It's About Time (1992)",
 'Amityville 3-D (1983)',
 'Amityville Curse, The (1990)',
 'Amityville Horror, The (1979)',
 'Amityville Horror, The (2005)',
 'Amityville II: The Possession (1982)',
 'Amityville: A New Generation (1993)',
 'Amityville: Dollhouse (1996)',
 "Amores Perros (Love's a Bitch) (2000)",
 'Amos & Andrew (1993)',
 'Amy (2015)',
 "Amy's O (a.k.a. Amy's Orgasm) (2001)",
 'An Amazing Couple (2002)',
 'Anacleto: Agente secreto (2015)',
 'Anaconda (1997)',
 'Anaconda: The Offspring (2008)',
 'Anacondas: The Hunt for the Blood Orchid (2004)',
 'Analyze That (2002)',
 'Analyze This (1999)',
 'Anarchist Cookbook, The (2002)',
 'Anastasia (1956)',
 'Anastasia (1997)',
 'Anatomy of a Murder (1959)',
 'Anchorman 2: The Legend Continues (2013)',
 'Anchorman: The Legend of Ron Burgundy (2004)',
 'Anchors Aweigh (1945)',
 'And God Created Woman (Et Dieu... crÃ©a la femme) (1956)',
 'And Now... Ladies and Gentlemen... (2002)',
 'And So It Goes (2014)',
 'And Starring Pancho Villa as Himself (2003)',
 'And Then There Were None (1945)',
 'And Your Mother Too (Y tu mamÃ¡ tambiÃ©n) (2001)',
 'And the Band Played On (1993)',
 'And the Ship Sails On (E la nave va) (1983)',
 'Andalusian Dog, An (Chien andalou, Un) (1929)',
 'Andre (1994)',
 'Andrei Rublev (Andrey Rublyov) (1969)',
 'Andrew Dice Clay: Dice Rules (1991)',
 'Android (1982)',
 'Andromeda Strain, The (1971)',
 'Angel Baby (1995)',
 'Angel Eyes (2001)',
 'Angel Heart (1987)',
 'Angel at My Table, An (1990)',
 "Angel's Egg (Tenshi no tamago) (1985)",
 'Angel-A (2005)',
 "Angela's Ashes (1999)",
 'Angels & Demons (2009)',
 'Angels and Insects (1995)',
 'Angels in the Outfield (1994)',
 'Angels with Dirty Faces (1938)',
 "Angels' Share, The (2012)",
 'Anger Management (2003)',
 'Angie (1994)',
 'Angriest Man in Brooklyn, The (2014)',
 'Angry Red Planet, The (1959)',
 'Angst  (1983)',
 'Angus (1995)',
 'Angus, Thongs and Perfect Snogging (2008)',
 'Animal Crackers (1930)',
 'Animal Factory (2000)',
 'Animal Farm (1954)',
 'Animal House (1978)',
 'Animal, The (2001)',
 'Animals are Beautiful People (1974)',
 'Animatrix, The (2003)',
 'Anna Christie (1930)',
 'Anna Karenina (1935)',
 'Anna Karenina (1997)',
 'Anna Karenina (2012)',
 'Anna and the King (1999)',
 'Annabelle (2014)',
 'Annabelle: Creation (2017)',
 'Annapolis (2006)',
 'Anne Frank Remembered (1995)',
 'Anne of Green Gables (1985)',
 'Anne of Green Gables: The Sequel (a.k.a. Anne of Avonlea) (1987)',
 'Anne of the Thousand Days (1969)',
 'Annie (1982)',
 'Annie Get Your Gun (1950)',
 'Annie Hall (1977)',
 'Annihilation (2018)',
 'Anniversary Party, The (2001)',
 'Anomalisa (2015)',
 'Another 48 Hrs. (1990)',
 'Another Cinderella Story (2008)',
 'Another Earth (2011)',
 'Another Gay Movie (2006)',
 'Another Stakeout (1993)',
 'Another Thin Man (1939)',
 'Another Woman (1988)',
 'Ant Bully, The (2006)',
 'Ant-Man (2015)',
 'Ant-Man and the Wasp (2018)',
 'Anthony Adverse (1936)',
 'Anti-Social (2015)',
 'Antichrist (2009)',
 'Antitrust (2001)',
 "Antonia's Line (Antonia) (1995)",
 'Antonio GaudÃ­ (1985)',
 'Antwone Fisher (2002)',
 'Antz (1998)',
 'Anvil! The Story of Anvil (2008)',
 'Any Given Sunday (1999)',
 'Any Which Way You Can (1980)',
 'Anything Else (2003)',
 'Anything for Her (Pour elle) (2008)',
 'Anything for Love (2016)',
 'Anywhere But Here (1999)',
 'Apartment, The (1960)',
 "Apartment, The (Appartement, L') (1996)",
 'Apocalypse Now (1979)',
 'Apocalypto (2006)',
 'Apollo 13 (1995)',
 'Apollo 18 (2011)',
 'Apostle, The (1997)',
 'Appaloosa (2008)',
 'Apple Dumpling Gang Rides Again, The (1979)',
 'Apple Dumpling Gang, The (1975)',
 'Apple, The (Sib) (1998)',
 'Applesauce (2015)',
 'Appleseed (AppurushÃ®do) (2004)',
 "April Fool's Day (1986)",
 'April Morning (1988)',
 'Apt Pupil (1998)',
 'Aqua Teen Hunger Force Colon Movie Film for Theaters (2007)',
 'Aquamarine (2006)',
 'Arachnophobia (1990)',
 'Ararat (2002)',
 'Are We Done Yet? (2007)',
 'Are We There Yet? (2005)',
 'Are You Scared? (2006)',
 'Argo (2012)',
 'Ari Shaffir: Double Negative (2017)',
 'Ariel (1988)',
 'Aristocats, The (1970)',
 'Aristocrats, The (2005)',
 'Arizona Dream (1993)',
 'Arlington Road (1999)',
 'Armageddon (1998)',
 'Armed and Dangerous (1986)',
 'Armour of God (Long xiong hu di) (1987)',
 'Armour of God II: Operation Condor (Operation Condor) (Fei ying gai wak) (1991)',
 'Army of Darkness (1993)',
 "Army of Shadows (L'armÃ©e des ombres) (1969)",
 'Around the World in 80 Days (1956)',
 'Around the World in 80 Days (2004)',
 'Arrival (2016)',
 'Arrival, The (1996)',
 'Arsenic and Old Lace (1944)',
 'Art School Confidential (2006)',
 'Art of Getting By, The (2011)',
 'Art of War, The (2000)',
 'Art of the Steal, The (2009)',
 'Art of the Steal, The (2013)',
 'Artemisia (1997)',
 'Arthur (1981)',
 'Arthur (2011)',
 'Arthur 2: On the Rocks (1988)',
 'Arthur Christmas (2011)',
 'As Above, So Below (2014)',
 'As Good as It Gets (1997)',
 'As I Was Moving Ahead Occasionally I Saw Brief Glimpses of Beauty (2000)',
 'As You Like It (2006)',
 'Ascent, The (Voskhozhdeniye) (1977)',
 'Ashby (2015)',
 'Ashes and Diamonds (PopiÃ³l i diament) (1958)',
 'Ashes of Time (Dung che sai duk) (1994)',
 'Ask the Dust (2006)',
 'Aspen Extreme (1993)',
 'Asphalt Jungle, The (1950)',
 'Asphyx, The (1973)',
 "Assassin's Creed (2016)",
 'Assassination (1987)',
 'Assassination Tango (2002)',
 'Assassination of Jesse James by the Coward Robert Ford, The (2007)',
 'Assassination of Richard Nixon, The (2004)',
 'Assassination of a High School President (2008)',
 'Assassins (1995)',
 'Assault on Precinct 13 (1976)',

In [25]:
example_movie_index = movies_list.index("Batman: Year One (2011)")

example_movie_index

852

In [26]:
example_correlations = correlation_matrix[example_movie_index]

example_correlations

array([ 0.38627055, -0.04496874,  0.0390084 , ...,  0.30864849,
        0.36793495,  0.25664935])

In [28]:
MAXIMUM_CORRELATION = 1.0
MINIMUM_CORRELATION = 0.9

list(movies_titles[(example_correlations < MAXIMUM_CORRELATION ) & (example_correlations > MINIMUM_CORRELATION)])

['Dead Pool, The (1988)',
 'Derailed (2005)',
 'Ghost Rider (2007)',
 'Great Mouse Detective, The (1986)',
 'Kid, The (2000)',
 'Kiss of the Dragon (2001)',
 'Mean Machine (2001)',
 'Open Water (2003)',
 'Queen of the Damned (2002)',
 'Raw Deal (1986)',
 'Return of Jafar, The (1994)',
 'Solo: A Star Wars Story (2018)',
 'Willard (2003)']